backend_app/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from backend_app import views

app_name = 'backend_app'

urlpatterns = [
 	path('admin/', admin.site.urls),
	path('', views.dashboard, name='dashboard'),
	path('register/', views.register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
	path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
 	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
 	
 	path('password_reset/', auth_views.PasswordResetView.as_view(
 		template_name='registration/password_reset.html',
 		email_template_name = 'registration/password_reset_email.html',
 		subject_template_name = 'registration/password_reset_subject.txt',
 		success_url = reverse_lazy('backend_app:password_reset_done')
 		),
 		name='password_reset'),
  	
  	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),
  	
	path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
		template_name='registration/password_reset_confirm.html',
		success_url = reverse_lazy('backend_app:password_reset_complete')
		), 
		name='password_reset_confirm'),
    
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    
    path('super_user/', views.ListSuperUser.as_view(), name='super_user'),
    path('regular_user/', views.ListRegularUser.as_view(), name='regular_user'),
    path('male/', views.ListMaleUser.as_view(), name='male'),
    path('female/', views.ListFemaleUser.as_view(), name='female'),
   
    

	path('profile/', views.profile, name='profile'),
	path('profile/edit/', views.edit_profile, name='edit_profile'),
	


	path('post/', views.CreatePost.as_view(), name='post'),
	path('list_post/', views.ListPost.as_view(), name='list_post'),
	path('edit_post/<int:pk>/', views.UpdatePost.as_view(), name='edit_post'),
	path('delete_post/<int:pk>/', views.DeletePost.as_view(), name='delete_post'),

  	

  	path('category/', views.CreateCategory.as_view(), name='category'),
	path('list_category/', views.ListCategory.as_view(), name='list_category'),
	path('edit_category/<int:pk>/', views.UpdateCategory.as_view(), name='edit_category'),
	path('delete_category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),


	path('user/', views.CreateUser.as_view(), name='user'),
	path('list_users/', views.ListUser.as_view(), name='list_user'),
	path('edit_users/<int:pk>/', views.UpdateUser.as_view(), name='edit_user'),
	path('delete_user/<int:pk>/', views.DeleteUser.as_view(), name='delete_user'),
	
	

 	
 	






	

	
	
]

frontend_app/urls.py
from django.urls import path
from frontend_app import views


app_name = 'frontend_app'

urlpatterns = [
	path('', views.blog, name='blog'),
	path('contact/', views.contact, name='contact'),
	path('blog_detail/<int:blog_id>', views.blog_detail, name='blog_detail'),
]

sam_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from frontend_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('frontend/', include('frontend_app.urls')),
    path('backend/', include('backend_app.urls')),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Home(models.Model):
	background_img = models.ImageField(verbose_name = 'Background Image', blank=True, null=True)
	name = models.CharField(verbose_name = 'Profile Name', max_length=100, default=None)
	home_desc = models.CharField(verbose_name = 'Home Description', max_length=200)
	
	def __str__(self):
		return self.name



class About(models.Model):
	about_img = models.ImageField(verbose_name = 'Background Image', blank=True, null=True)
	name = models.CharField(verbose_name = 'Full Name', max_length=100, default=None)
	about_desc = models.CharField(verbose_name = 'About Description', max_length=100)
	email = models.EmailField(default=None, max_length=254, blank=False, unique=True,
		        error_messages={'required': 'Please provide your email address.',
		                        'unique': 'An account with this email exist.'},)
	phone_number = models.CharField(verbose_name = 'Mobile Number' , blank=True, null=True, max_length=20)
	about_cont = models.TextField(verbose_name = 'About Content')

# KNOWLEDGE
	HTML5 = models.CharField(verbose_name = 'HTML5' , blank=True, null=True, max_length=3)
	CSS3 = models.CharField(verbose_name = 'CSS3' , blank=True, null=True, max_length=3)
	PYTHON = models.CharField(verbose_name = 'PHYHON' , blank=True, null=True, max_length=3)
	GIT = models.CharField(verbose_name = 'GIT' , blank=True, null=True, max_length=3)

	def __str__(self):
		return self.name



class Qualification(models.Model):
	qualification_title = models.CharField(verbose_name='Qualification Description', max_length=100, default=None)
	qualification_desc = models.TextField(verbose_name='Qualification Content')
	
	def __str__(self):
		return self.qualification_title



class Portfolio(models.Model):
	portfolio_img = models.ImageField(verbose_name = 'Portfolio Image', blank=True, null=True)
	portfolio_title = models.CharField(verbose_name='Portfolio Title', max_length=100)
	portfolio_desc = models.TextField(verbose_name='Portfolio Description')
	last_edited = models.DateTimeField(auto_now = True)

	def __str__(self):
		return self.portfolio_title


class Category(models.Model):
	name = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	

class Blog(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	blog_img = models.ImageField(verbose_name = 'Blog Image', blank=True, null=True)
	blog_desc = models.CharField(verbose_name = 'Blog Description', max_length=200)
	author_image = models.ImageField(verbose_name = 'Author Image', blank=True, null=True)
	blog_author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Blog Author')
	published_date = models.DateTimeField(blank=True, null=True)
	content = models.TextField(verbose_name='Content', blank=True, null=True)
	
	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.blog_desc


class Banner(models.Model):
	banner_for_blog = models.ImageField(verbose_name = 'Banner Image', blank=True, null=True)
	banner_title = models.CharField(verbose_name = 'Banner Title', max_length=250, default='')
	banner_description = models.CharField(verbose_name = 'Banner Description', max_length=300, default='')
	published_date = models.DateTimeField(blank=True, null=True)

	def __str__(self):
		return str(self.banner_for_blog)



class ContactForm(models.Model):
	name = models.CharField(verbose_name='Name', max_length=150)
	email = models.EmailField()
	subject = models.CharField(verbose_name='Subject', max_length=150)
	message = models.TextField(verbose_name='Message', blank=True, null=True)

	def __str__(self):
		return self.name


class Marquee(models.Model):
	message = models.TextField(verbose_name='Message', blank=True, null=True)

	def __str__(self):
		return self.message

frontend_app/forms.py
from django import forms
from frontend_app.models import ContactForm
 

class ContactForm(forms.ModelForm):
     class Meta():
          model = ContactForm
          fields = ('name', 'email', 'subject', 'message')
          widgets = {
               'name' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter your Full Name', 'size':70}),
               'email' : forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter your email', 'size':70}),
               'subject': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please enter your Subject', 'size':70}),
               'message' : forms.Textarea(attrs={'class':'form-control', 'placeholder':'Type your Message Here', 'size':70}),

          }

frontend_app/views.py
from django.shortcuts import render, redirect
from django.template.loader import get_template 
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from frontend_app.models import Home, About, Qualification, Portfolio, Blog, ContactForm, Banner, Marquee
from frontend_app.forms import ContactForm
from django.contrib.auth.models import User
from django.contrib import messages


# Create your views here.

def index(request):
	show_home = Home.objects.all()
	show_about = About.objects.all()
	show_qualification = Qualification.objects.all()
	show_portfolio = Portfolio.objects.all()
	
	
	index_dict = {
		'home_list':show_home,
		'about_list':show_about,
		'qualification_list':show_qualification,
		'portfolio_list':show_portfolio,

	}
	return render(request, 'frontend_app/index.html', context=index_dict)



def blog(request):
	show_banner = Banner.objects.all()
	show_blog = Blog.objects.all()
	show_marquee = Marquee.objects.all()
	latest = Blog.objects.order_by('-last_edited')[0:3]

	blog_dict = {
		'banner_list':show_banner,
		'blog_list':show_blog,
		'marquee_list':show_marquee,
		'latest':latest
	}
	return render(request, 'frontend_app/blog.html', context=blog_dict)


def blog_detail(request, blog_id):
	blog_detail = Blog.objects.get(pk=blog_id)
	return render(request, 'frontend_app/blog_detail.html', {'blog_det':blog_detail})


	search_term=''
	if 'search' in request.GET:
		search_term = request.GET['search']
		blog_detail = blog_detail.filter(text__icontains="")
	
	return render(request, 'frontend_app/blog_detail.html', {'search_term':search_term})



	

def contact(request):
	Contact_Form = ContactForm
	if request.method == 'POST':
		form = Contact_Form(data=request.POST)

		if form.is_valid():
			form.save()
			messages.success(request, 'We have received your message and would like to thank you for writing to us. If your inquiry is urgent, please use the telephone number listed below to talk to one of our staff members. Otherwise, we will reply by email as soon as possible.')
			name = request.POST.get('name')
			email = request.POST.get('email')
			subject = request.POST.get('subject')
			message = request.POST.get('message')

			template = get_template('frontend_app/contact.txt')
			context = {
				'name' : name,
				'email' : email,
				'subject' : subject,
				'message' : message,
			}
			
			content = template.render(context)
			email = EmailMultiAlternatives(
				'New message from Python Project',
				content,
				'Code with Sam' + '',
				['mrsaharuna@gmail.com'],
			headers = { 'Reply To': email }
			)

		email.send()
		return redirect('frontend_app:contact')

	else:
		form = ContactForm()
	return render(request, 'frontend_app/contact.html', { 'form':Contact_Form })

templates/frontend_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>
  {% block title %}

  {% endblock %}
  </title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Montserrat&display=swap' %}" rel="stylesheet">
  <link href="{% static 'https://fonts.googleapis.com/css?family=Roboto&display=swap' %}" rel="stylesheet">
  <link href="{% static 'https://fonts.googleapis.com/css?family=Lato:700|Roboto+Slab&display=swap' %}" rel="stylesheet">

  <!-- Favicons -->
  <link href="{% static 'frontend_app/images/small.jpg' %}" rel="icon">
  <link href="{% static 'frontend_app/images/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'frontend_app/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'frontend_app/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'frontend_app/lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'frontend_app/lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'frontend_app/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'frontend_app/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'frontend_app/css/style.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!--/ Nav Star /-->
  <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll" href="{% static 'frontend/#page-top' %}">  </a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll active" href="{% url 'index' %}#home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'index' %}#about">ABOUT ME</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'index' %}#qualifications">QUALIFICATIONS</a>
          </li>

          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'index' %}#work">PORTFOLIO</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'frontend_app:blog' %}">BLOG</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'frontend_app:contact' %}">CONTACT US</a>
          </li>
        </ul>
        <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link js-scroll" href = "{% url 'backend_app:login' %}">Login</a>
            </li>

            <li class="nav-item">
               <a class="nav-link js-scroll" href = "{% url 'backend_app:register' %}">Register</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <!--/ Nav End /-->
  
  {% block content %}

  {% endblock %}

  
  <!-- footer -->

  <footer>
      <div class="widgetd-sidebar widget-tags pt-5">
        <div class="sidebar-content">
          <ul>
            <li>
              <a href="https://alabiansolutions.com/web-development/" target="_blank">Software Development</a>
            </li>
            <li>
              <a href="https://alabiansolutions.com/webtraining/" target="_blank">PHP</a>
            </li>
            <li>
              <a href="https://alabiansolutions.com/javascript-development-training/" target="_blank">JavaScript</a>
            </li>
            <li>
              <a href="https://alabiansolutions.com/graphics-design/" target="_blank">Graphic Design</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="copyright-box">
              <p class="copyright">&copy; Copyright <strong>2019</strong>. All Rights Reserved</p>
              <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=DevFolio
                -->
                Designed by Mr Sam
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </section>
  <!--/ Section Contact-footer End /-->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <div id="preloader"></div>

  <!-- JavaScript Libraries -->
  <script src="{% static 'frontend_app/lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/popper/popper.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/counterup/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/counterup/jquery.counterup.js' %}"></script>
  <script src="{% static 'frontend_app/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/lightbox/js/lightbox.min.js' %}"></script>
  <script src="{% static 'frontend_app/lib/typed/typed.min.js' %}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{% static 'frontend_app/contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'frontend_app/js/main.js' %}"></script>

templates/frontend_app/blog.html
{% extends 'frontend_app/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
Blog
{% endblock %}

{% block content %}


<section class="banner pt-1">
  {% for banner in banner_list %}
  <div class="container">
    <div class="text-center text-dark bg-white border border-dark font-weight-bold ">
        <span><font size="8" color="green" face="Agency FB">{{ banner.banner_title }}</font></span><br/>
        <span><font size="3" face="Arial Black">{{ banner.banner_description }}</font></span>
    </div>

    <div>
      <img src="{{ banner.banner_for_blog.url }} " alt=""  class="img-fluid">
    </div>
   
  </div>
  {% endfor %}
<div class="container marquee pt-1" >
{% for marquee in marquee_list %}
    <marquee behavior="" direction=""><font color="red" size="4" face="Arial Black"><strong>Breaking News:    </strong></font><font size="4" color="white" face="Arial Black">{{ marquee.message }}</font> </marquee>
{% endfor %}  
</div>
</section>

<section id="blog" class="blog-mf sect-pt4 route mt-5">
  <div class="container">
    <div class="row">
    {% if blog_list %}
      {% for blog in blog_list %}
      <div class="col-md-4 bg-white">
        <div class="card card-blog border border-success">
          <div class="card-img">
             <a href="blog_detail/{{ blog.id }}">
            <img src="{{ blog.blog_img.url }}" alt="Blog Image" class="img-fluid"></a>
          </div>
          <div class="card-body">
            <div class="card-category-box">
              <div class="card-category">
                <h2 class="category">{{ blog.category }}</h2>
              </div>
            </div>
            <p class="card-title para lead">{{ blog.blog_desc }}      <a href="blog_detail/{{ blog.id }}" class="readmore btn btn-success"><strong>Readmore</strong></a></p>  
          </div>
            <div class="card-footer">
            <div class="post-author">
              <a href="#">
                <img src="{{ blog.author_image.url }}" alt="" class="avatar rounded-circle">
                <span class="author"> {{ blog.blog_author }}</span>
              </a>
            </div>
            <div class="post-date">
              <span class="ion-ios-clock-outline">{{ blog.published_date }}</span>
            </div>
          </div>
        </div>
      </div>
    
      {% endfor %}
      {% else %}
      <p>No Blog Content Please</p>
    {% endif %}
    </div>
  </div>
</section>
<!--/ Section Blog End /-->
{% endblock %}

templates/frontend_app/blog_detail.html
{% extends 'frontend_app/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
Blog Detail
{% endblock %}

{% block content %}
<section id="blog" class="blog-mf sect-pt4 route">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="title-box text-center">
          <div class="line-mf"></div>
        </div>
      </div>
    </div>
  </div>
</section>
  <!--/ Section Blog-Single Star /-->
  <section class="blog-wrapper " id="blog">
    <div class="container">
      <div class="row">
        <div class="col-md-8 border border-white bg-dark">
          <div class="post-box">
            {% if blog_det %}
            <h3 class="para">{{ blog_det.blog_desc }}</h3>
            <div class="post-thumb">
             <img src="{{ blog_det.blog_img.url }}" alt="" class="img-fluid border border-success">
            </div>
            <div class="post-meta">
              <ul>
                <li>
                  <span class="ion-pricetag"></span>
                  <a href="#">{{ blog_det.category }}</a>
                </li>
                <li>
                  <span class="ion-clock"></span>
                  <a href="#">{{ blog_det.published_date }}</a>
                </li>
              </ul>
            </div>
            <div class="article-content para lead">
             <p>{{ blog_det.content | linebreaks }}</p>
            </div>
          </div>
          {% endif %}
        </div>
        {% include 'frontend_app/sidebar.html' %}
        </div>
      </div>
    </div>
  </section>

   
{% endblock %}

templates/frontend_app/contact.html
{% extends 'frontend_app/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Contact US
{% endblock %}
{% load crispy_forms_tags %}


{% block content %}

  <section class="paralax-mf footer-paralax bg-image sect-mt4 route" style="background-image: url({% static 'frontend/images/Coding.jpg' %})">
    <div class="overlay-mf"></div>
     <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="contact-mf">
            <div id="contact" class="box-shadow-full">
               <div class="title-box text-center">
                <h1 class="title-a">
                CONTACT US
                </h1>
                <div class="line-mf"></div>
                </div>
                {% if messages %}
                   {% for message in messages %}
                   <div class="alert alert-{% if message.tags == 'error' %}Danger{% else %}{{ message.tags }} {% endif %}" role="alert">
                      {{ message }}
                   </div>
                   {% endfor %}
                {% endif %}

              <div class="row">
                <div class="col-md-6">
                  <div class="title-box-2">
                    <h3 class="title-left">
                    Get in Touch
                    </h3>
                </div>
                <div>    
                  <form action="" method="POST">
                    <div class="row">
                  
                      {{ form|crispy }}
                   
                      {% csrf_token %}
                      <div class="col-md-12">
                        <button type="submit" class="btn btn-success">Send Message</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
                <div class="col-md-6">
                  <div class="title-box-2 pt-4 pt-md-0">
                    <h3 class="title-left">
                      For More Information
                    </h3>
                  </div>
                  <div class="more-info">
                    <ul class="list-ico">
                     Visit Us at Our Address below;
                      <li class="para"><span class="ion-ios-location"></span>By PHCN Office, Foursquare Gospel Church, 5th Avenue, 51 Road, Gowon Estate, Egbeda, Lagos State</li>
                      Call (Text) or Email Us;
                      <li><span class="ion-ios-telephone"></span>(234)7037678697</li>
                      <li><span class="ion-email"></span>samsonharuna@yahoo.com</li>
                    </ul>
                  </div>
                  <div class="socials">
                    <ul>
                      <li><a href="https://www.facebook.com" target="_blank"><span class="ico-circle"><i class="ion-social-facebook"></i></span></a></li>
                      <li><a href="https://www.instagram.com" target="_blank"><span class="ico-circle"><i class="ion-social-instagram"></i></span></a></li>
                      <li><a href="https://www.twitter.com" target="_blank"><span class="ico-circle"><i class="ion-social-twitter"></i></span></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/frontend_app/sidebar.html
 <div class="col-md-4">
    <div class="widget-sidebar sidebar-search">
      <h5 class="sidebar-title">Search</h5>
      <div class="sidebar-content">
        
        <form class="form-inline my-2 my-lg-2">
          <div class="input-group">
            <input type="search" class="form-control" placeholder="Search" aria-label="Search" name="search" value="{{ search_term }}">
            <span class="input-group-btn">
              <button class="btn btn-secondary btn-search" type="submit">
                <span class="ion-android-search"></span>
              </button>
            </span>
          </div>
        </form>

      </div>
    </div>  

    <div class="widget-sidebar">
        <h5 class="sidebar-title">Menu</h5>
          <div class="sidebar-content">
              <ul class="list-sidebar">

                <li class="nav-item">
                  <a class="nav-link js-scroll active" href="{% url 'index' %}#home">HOME</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link js-scroll" href="{% url 'index' %}#about">ABOUT ME</a>
                </li>
                    
                <li class="nav-item">
                  <a class="nav-link js-scroll" href="{% url 'index' %}#qualifications">QUALIFICATIONS</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link js-scroll" href="{% url 'index' %}#work">PORTFOLIO</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link js-scroll" href="{% url 'frontend_app:blog' %}">BLOG</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link js-scroll" href="{% url 'index' %}#contact">CONTACT</a>
                </li>
              </ul>
        </div>
    </div>

     <div class="widget-sidebar widget-tags">
            <h5 class="sidebar-title">Tags</h5>
            <div class="sidebar-content">
              <ul>
                <li>
                  <a href="https://alabiansolutions.com/web-development/">Software Development</a>
                </li>
                <li>
                  <a href="https://alabiansolutions.com/webtraining/">PHP</a>
                </li>
                <li>
                  <a href="https://alabiansolutions.com/javascript-development-training/">JavaScript</a>
                </li>
                <li>
                  <a href="https://alabiansolutions.com/graphics-design/">Graphic Design</a>
                </li>
              </ul>
            </div>
          </div>
  </div>
  