backend_app/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from backend_app import views

app_name = 'backend_app'

urlpatterns = [
 	path('admin/', admin.site.urls),
	path('', views.dashboard, name='dashboard'),
	path('register/', views.register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
	path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
 	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
 	
 	path('password_reset/', auth_views.PasswordResetView.as_view(
 		template_name='registration/password_reset.html',
 		email_template_name = 'registration/password_reset_email.html',
 		subject_template_name = 'registration/password_reset_subject.txt',
 		success_url = reverse_lazy('backend_app:password_reset_done')
 		),
 		name='password_reset'),
  	
  	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),
  	
	path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
		template_name='registration/password_reset_confirm.html',
		success_url = reverse_lazy('backend_app:password_reset_complete')
		), 
		name='password_reset_confirm'),
    
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    
    path('super_user/', views.ListSuperUser.as_view(), name='super_user'),
    path('regular_user/', views.ListRegularUser.as_view(), name='regular_user'),
    path('male/', views.ListMaleUser.as_view(), name='male'),
    path('female/', views.ListFemaleUser.as_view(), name='female'),
   
    

	path('profile/', views.profile, name='profile'),
	path('profile/edit/', views.edit_profile, name='edit_profile'),
	


	path('post/', views.CreatePost.as_view(), name='post'),
	path('list_post/', views.ListPost.as_view(), name='list_post'),
	path('edit_post/<int:pk>/', views.UpdatePost.as_view(), name='edit_post'),
	path('delete_post/<int:pk>/', views.DeletePost.as_view(), name='delete_post'),

  	

  	path('category/', views.CreateCategory.as_view(), name='category'),
	path('list_category/', views.ListCategory.as_view(), name='list_category'),
	path('edit_category/<int:pk>/', views.UpdateCategory.as_view(), name='edit_category'),
	path('delete_category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),


	path('user/', views.CreateUser.as_view(), name='user'),
	path('list_users/', views.ListUser.as_view(), name='list_user'),
	path('edit_users/<int:pk>/', views.UpdateUser.as_view(), name='edit_user'),
	path('delete_user/<int:pk>/', views.DeleteUser.as_view(), name='delete_user'),
	
	

 	
 	






	

	
	
]

sam_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from frontend_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('frontend/', include('frontend_app.urls')),
    path('backend/', include('backend_app.urls')),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_app/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

# Create your models here.


class MaleManager(models.Manager):
    def get_query_set(self):
        return super(MaleManager, self).get_query_set().filter(sex='M')

class FemaleManager(models.Manager):
    def get_query_set(self):
        return super(FemaleManager, self).get_query_set().filter(sex='F')

class UserProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE, unique=True)
	email = models.EmailField(max_length=250, default='', unique=True)
	password = forms.CharField(widget=forms.PasswordInput)
	password_again = forms.CharField(widget=forms.PasswordInput)
	first_name = models.CharField(max_length=100, default='')
	last_name = models.CharField(max_length=100, default='')
	image = models.ImageField(upload_to='uploads/profile_image', blank=True)
	sex = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female')))
	role = models.CharField(max_length=1, choices=[('S', _('Super')), ('R', _('Regular'))])
	active = models.BooleanField(default=True)
	
	
	def __str__(self):
		return self.user.username


class Category(models.Model):
	name = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name


class Post(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	post_title = models.CharField(verbose_name='Post Title', max_length=50)
	content = models.TextField(verbose_name='Content', blank=True, null=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
	post_img = models.ImageField(blank=True, null=True, upload_to='uploads/post_img', verbose_name='Post Image')
	published_date = models.DateTimeField(default=timezone.now, blank=True, null=True)
	
	

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.post_title

backend_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm, UserChangeForm
from backend_app.forms import (RegForm, EditUserForm, PostForm, 
    CategoryForm, AuthenticationForm, UserForm)
from django.contrib.auth import update_session_auth_hash 
from django.contrib import messages
from django.contrib.auth import authenticate
from backend_app.models import Post, Category, UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (ListView, DetailView, UpdateView, DeleteView, CreateView)
from django.contrib.auth.models import User
from typing import List
from django.urls import reverse_lazy
from django.db.models import Count

# Create your views here.

@login_required
def dashboard(request):
  post_count = Post.objects.count()
  category_count = Category.objects.count()
  super_user_count = UserProfile.objects.count()
  regular_user_count = UserProfile.objects.count()
  male_count = UserProfile.objects.count()
  female_count = UserProfile.objects.count()

  return render(request, 'backend_app/index.html', {'post_count': post_count, 
    'category_count': category_count, 
    'super_user_count': super_user_count,
    'regular_user_count': regular_user_count,
    'male_count': male_count,
    'female_count': female_count,
    })


class ListSuperUser(ListView):
  model = UserProfile
  template_name = 'backend_app/super_user.html'
  context_object_name = 'super_user'


class ListRegularUser(ListView):
  model = UserProfile
  template_name = 'backend_app/regular_user.html'
  context_object_name = 'regular_user'


class ListMaleUser(ListView):
  model = UserProfile
  template_name = 'backend_app/male.html'
  context_object_name = 'male'


class ListFemaleUser(ListView):
  model = UserProfile
  template_name = 'backend_app/female.html'
  context_object_name = 'female'


@login_required
def user(request):
  if request.method == 'POST':
    add_user= AddUser(request.POST)
    if user.is_valid():
      user.save()
      messages.success(request, 'User added successfully.')
      return redirect('backend_app:user')
  else:
    user = User()
  context = {'user':user}
  return render(request, "backend_app/user.html", context)



@login_required
def logout(request):
    return render(request, 'registration/logout.html')



def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('backend_app:index')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request = request,
                    template_name = "registration/login.html",
                    context={"form":form})



def register(request):
    form = RegForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your Registration was done successfully, Click on the Login button below to Login')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        return redirect('backend_app:register')
    else:
        form = RegForm()
    return render(request, 'registration/register.html', {'form': form})



@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, form.user)  
            messages.success(request, 'Your password was successfully updated!')
            return redirect('backend_app:password_change')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'registration/password_change.html', {'form': form})



@login_required
def password_reset(request):
    if request.method == 'POST':
        form = SetPasswordForm(request=request, data=request.POST)
        if form.is_valid():
            messages.success(request, 'Your Password was Reset successfully updated!')
            password1 = form.cleaned_data.get('new_password1')
            password2 = form.cleaned_data.get('new_password2')
            user = set_password(password1=password1, password2=password2)
            if user is not None:
                set_password(request, user)
                return redirect('password_reset')
            else:
                messages.error(request, "password_mismatch")
        else:
            messages.error(request, "password_mismatch")
    form = SetPasswordForm()
    return render(request = request,
                    template_name = "registration/password_reset.html",
                    context={"form":form})


@login_required
def password_reset_confirm(request, uidb64, token):
    try:
        uid_int = base36_to_int(uidb36)
    except ValueError:
        raise Http404

    user = get_object_or_404(User, id=uid_int)
    context = {}

    if default_token_generator.check_token(user, token):
        context["validlink"] = True
        if request.method == "POST":
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                return redirect('backend_app:password_reset_complete')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = SetPasswordForm(user=request.user)
        
    return render(request, "registration/password_reset_confirm.html", {'form': form})



@login_required    
def password_reset_done(request):
  return redirect('backend_app:password_reset_confirm')
  return render(request, "registration/password_reset_done.html")



@login_required    
def password_reset_complete(request):
  return render(request, "registration/password_reset_complete.html")


@login_required  
def edit_profile(request):
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Profile was successfully updated!')
            return redirect('backend_app:profile')
    else:
        form = EditUserForm(instance=request.user)
        context = {'form': form}
        return render(request, 'backend_app/edit_profile.html', context)

def profile(request):
    args = {'user': request.user}
    return render(request, 'backend_app/profile.html', args)



class CreatePost(CreateView):
  model = Post
  form_class = PostForm
  template_name = 'backend_app/post.html'
  success_url = reverse_lazy('backend_app:list_post')

class ListPost(ListView):
  model = Post
  template_name = 'backend_app/list_post.html'
  context_object_name = 'list_post'

class UpdatePost(UpdateView):
  model = Post
  form_class = PostForm
  template_name = 'backend_app/edit_post.html'
  success_url = reverse_lazy('backend_app:list_post')

class DeletePost(DeleteView):
  model = Post
  template_name = 'backend_app/delete_post.html'
  success_url = reverse_lazy('backend_app:list_post')




class CreateCategory(CreateView):
  model = Category
  form_class = CategoryForm
  template_name = 'backend_app/category.html'
  success_url = reverse_lazy('backend_app:list_category')

class ListCategory(ListView):
  model = Category
  template_name = 'backend_app/list_category.html'
  context_object_name = 'list_category'

class UpdateCategory(UpdateView):
  model = Category
  form_class = CategoryForm
  template_name = 'backend_app/edit_category.html'
  success_url = reverse_lazy('backend_app:list_category')

class DeleteCategory(DeleteView):
  model = Category
  template_name = 'backend_app/delete_category.html'
  success_url = reverse_lazy('backend_app:list_category')



class CreateUser(CreateView):
  model = UserProfile
  form_class = UserForm
  template_name = 'backend_app/user.html'
  success_url = reverse_lazy('backend_app:user')

class ListUser(ListView):
  model = UserProfile
  template_name = 'backend_app/list_user.html'
  context_object_name = 'list_user'

class UpdateUser(UpdateView):
  model = UserProfile
  form_class = UserForm
  template_name = 'backend_app/edit_user.html'
  success_url = reverse_lazy('backend_app:list_user')

class DeleteUser(DeleteView):
  model = UserProfile
  template_name = 'backend_app/delete_user.html'
  success_url = reverse_lazy('backend_app:list_user')

templates/backend_app/backend_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
    {% block title %}

    {% endblock %}
    {% load crispy_forms_tags %}
    </title>
    <!-- Google Fonts -->
    <link href="{% static 'https://fonts.googleapis.com/css?family=Montserrat&display=swap' %}" rel="stylesheet">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Roboto&display=swap' %}" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="32x30" href="{% static 'backend_app/images/favicon.png' %}">
    <link href="{% static 'backend_app/css/admin.css' %}" rel="stylesheet">
  </head>
  <body id="admin">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3" id="top-sidebar">
         <a href="{% url 'backend_app:regular_user' %} ">
           <img src="{% static 'backend_app/images/admin-logo.png' %}" class="img-responsive">
         </a>
        </div>
        <div class="col-sm-9" id="top-content">
         <div class="status pull-right">
           <img src="{{ user.userprofile.image.url }}" class="img-circle">
           <div class="userStatus">
             <a class="userStatus dropdown-toggle" data-toggle="dropdown" id="userStatus">
              {{ user.first_name }}
              <span class="caret"></span>
             </a>
             <ul class="dropdown-menu">
              <li><a href="{% url 'backend_app:logout' %}">Log Out</a></li>
              <li><a href="{% url 'backend_app:password_change' %}">Change Password</a></li>
              <li><a href="{% url 'backend_app:profile' %}">View Profile</a></li>
              <li><a href="{% url 'backend_app:edit_profile' %}">Edit Profile</a></li>
             </ul>
           </div>
         </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2" id="adim-sidebar">
          <div class="row">
            <div class="col-sm-4">
              <img src="{{ user.userprofile.image.url }}" class="img-circle">
            </div>
            <div class="col-sm-0">
              <span>{{ user.first_name }}</span><br>
              <span class="fa fa-circle text-success"></span>
              Online<br>
            </div>
          </div>
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                     Posts
                     <span class="pull-right"> 
                       <span class="fa fa-angle-left"></span>
                     </span>
                   </a>
                </h4>
              </div>
              <div id="collapse1" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul class="nav">
                    <li>
                      <a href="{% url 'backend_app:post' %}">
                        <span class="fa fa-circle-o"></span>
                         Add Post
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'backend_app:list_post' %}">
                        <span class="fa fa-circle-o"></span>
                        View Posts
                      </a>
                    </li> 
                  </ul>
                </div>
              </div>
            </div>
            
           <div class="panel panel-default">
             <div class="panel-heading">
               <h4 class="panel-title">
                 <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                   Category
                   <span class="pull-right"> 
                     <span class="fa fa-angle-left"></span>
                   </span>
                 </a>
               </h4>
             </div>
             <div id="collapse2" class="panel-collapse collapse">
               <div class="panel-body">
                 <ul class="nav">
                   <li>
                     <a href="{% url 'backend_app:category' %}">
                       <span class="fa fa-circle-o"></span>
                       Add Category
                     </a>
                   </li>
                   <li>
                     <a href="{% url 'backend_app:list_category' %}">
                       <span class="fa fa-circle-o"></span>
                       View Category
                     </a>
                   </li>
                 </ul>
               </div>
             </div>
          
             <div class="panel panel-default">
               <div class="panel-heading">
                 <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                   Users</a>
                 </h4>
               </div>
               <div id="collapse3" class="panel-collapse collapse">
                 <div class="panel-body">
                   <ul class="nav">
                     <li><a href="{% url 'backend_app:user' %}">Add User</a></li>
                     <li><a href="{% url 'backend_app:list_user' %}">View Users</a></li>
                   </ul>
                 </div>
               </div>
             </div>

           </div>
    {% block content %}


    {% endblock %}
  <script src="{% static 'backend_app/js/jquery.js' %}"></script>
  <script src="{% static 'backend_app/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/backend_app/delete_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    Admin
    {% endblock %}
    {% load crispy_forms_tags %}
    
    <link rel="icon" type="image/png" sizes="32x30" href="{% static 'backend_app/images/favicon.png' %}">
    <link href="{% static 'backend_app/css/admin.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body id="admin">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3" id="top-sidebar">
         <a href="{% url 'backend_app:regular_user' %}">
           <img src="{% static 'backend_app/images/admin-logo.png' %}" class="img-responsive">
         </a>
        </div>
        <div class="col-sm-9" id="top-content">
         <div class="status pull-right">
           <img src="{{ user.userprofile.image.url }}" class="img-circle">
           <div class="userStatus">
             <a class="userStatus dropdown-toggle" data-toggle="dropdown" id="userStatus">
              {{ user.first_name }}   
              <span class="caret"></span>
             </a>
             <ul class="dropdown-menu">
              <li><a href="{% url 'backend_app:logout' %}">Log Out</a></li>
              <li><a href="{% url 'backend_app:password_change' %}">Change Password</a></li>
              <li><a href="{% url 'backend_app:edit_profile' %}">Edit Profile</a></li>
             </ul>
           </div>
         </div>
        </div>
      </div>
      <div class="row">
        
        <div class="col-sm-3" id="adim-sidebar">
          <div class="row">
            <div class="col-sm-3">
              <img src="{{ user.userprofile.image.url }}" class="img-circle">
            </div>
            <div class="col-sm-9">
              <span>{{ user.first_name }}</span><br>
              <span class="fa fa-circle text-success"></span>
              Online<br>
            </div>
          </div>
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                     Posts
                     <span class="pull-right"> 
                       <span class="fa fa-angle-left"></span>
                     </span>
                   </a>
                </h4>
              </div>
              <div id="collapse1" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul class="nav">
                    <li>
                      <a href="{% url 'backend_app:post' %}">
                        <span class="fa fa-circle-o"></span>
                         Add Post
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'backend_app:list_post' %}">
                        <span class="fa fa-circle-o"></span>
                        View Posts
                      </a>
                    </li> 
                  </ul>
                </div>
              </div>
            </div>
           <div class="panel panel-default">
             <div class="panel-heading">
               <h4 class="panel-title">
                 <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                   Category
                   <span class="pull-right"> 
                     <span class="fa fa-angle-left"></span>
                   </span>
                 </a>
               </h4>
             </div>
             <div id="collapse2" class="panel-collapse collapse">
               <div class="panel-body">
                 <ul class="nav">
                   <li>
                     <a href="{% url 'backend_app:category' %}">
                       <span class="fa fa-circle-o"></span>
                       Add Category
                     </a>
                   </li>
                   <li>
                     <a href="{% url 'backend_app:list_category' %}">
                       <span class="fa fa-circle-o"></span>
                       View Category
                     </a>
                   </li>
                 </ul>
               </div>
             </div>
           </div>
           <div class="panel panel-default">
             <div class="panel-heading">
               <h4 class="panel-title">
                 <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                 Users</a>
               </h4>
             </div>
             <div id="collapse3" class="panel-collapse collapse">
               <div class="panel-body">
                 <ul class="nav">
                   <li><a href="{% url 'backend_app:user' %}">Add User</a></li>
                   <li><a href="{% url 'backend_app:list_user' %}">View Users</a></li>
                 </ul>
               </div>
             </div>
           </div>
          </div>
        </div>

        <div class="col-sm-9" id="admin-main-content">
          <div class="row">
              <div class="col-md-10 col-md-offset-1">
               <div class="post-content">
                 <h3>
                  Do you want to Delete this Post?
                </h3>
                 <form method="post" action="">
                  {% csrf_token %}
                 
                  {{ form|crispy }}
                 
                      <input type="submit" class="btn btn-danger btn-block" value="Yes">

                      <a href="{% url 'backend_app:list_post' %}"><input type="" class="btn btn-success btn-block" value="No"></a>
                 </form>
                </div>
              </div>
             </div>
           </div>
          </div>
    </div>
    <script src="{% static 'backend_app/js/jquery.js' %}"></script>
    <script src="{% static 'backend_app/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'backend_app/tinymce/init.tinymce.js' %}"></script>
    <script src="{% static 'backend_app/js/bootstrap.min.js' %}"></script>
</body>
</html>
            

templates/backend_app/index.html
{% extends 'backend_app/backend_base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Dashboard
{% endblock %}
{% load crispy_forms_tags %}



{% block content %}
        
          </div>
        </div>
        <div class="col-sm-9" id="admin-main-content">
          <div class="row">
            <div class="col-sm-2">
             <div class="inner-box">
               <a href="{% url 'backend_app:super_user' %}"> 
                <i class="fa fa-lock"></i> 
                 <span>{{ super_user_count }}</span>
                <h4> Super Users</h4>
               </a>
             </div>
            </div>         
            <div class="col-sm-2">
             <div class="inner-box">
               <a href="regular_user/{{ reg_user.id }}"> 
                <i class="fa fa-users"></i>
                <span>{{ regular_user_count }}</span>
                <h4>Regular Users</h4>
               </a>
             </div>
            </div> 
            <div class="col-sm-2">
             <div class="inner-box">
               <a href="{% url 'backend_app:male' %}"> 
                <i class="fa fa-male"></i> 
                 <span>{{ male_count }}</span>
                 <h4> Male</h4>
                 <span class="little-text">Subscribers</span>
               </a>
             </div>
            </div> 
            <div class="col-sm-2">
             <div class="inner-box">
               <a href="{% url 'backend_app:female' %}"> 
                <i class="fa fa-female"></i> 
                <span>{{ female_count }}</span>
                <h4>Female</h4>
                <span class="little-text">Subscribers</span>
               </a>
             </div>
            </div> 
            <div class="col-sm-2">
             <div class="inner-box">
               <a href="{% url 'backend_app:list_post' %}"> 
                <i class="fa fa-pencil-square-o"></i>
                <span>{{ post_count }}</span>
                <h4>Posts</h4>
               </a>
             </div>
            </div>
            <div class="col-sm-2">
             <div class="inner-box">
               <a href="{% url 'backend_app:list_category' %}"> 
                <i class="fa fa-object-group"></i>
                <span>{{ category_count }}</span>
                <h4>Categories</h4>
               </a>
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/backend_app/list_user.html
{% extends 'backend_app/backend_base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Admin
{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
          </div>
        </div>
        <div class="col-sm-9" id="admin-main-content">
          <div class="row">
              <div class="col-md-10 col-md-offset-1">
               <div class="post-content">
                 <h3>View Users</h3>
                <table class="table table-bordered">
                  <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th colspan="2">Action</th>
                  </tr>
                  {% if list_user %}
                  {% for key in list_user %}
                  <tr>
                    <td>{{ key.user }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ key.first_name }}</td>
                    <td>{{ key.last_name }}</td>
                    <td>
                      <form method="post" action="">
                        {% csrf_token %}
                        <button type="button" class="btn btn-danger">
                          <a href="{% url 'backend_app:delete_user' pk=key.id %}"><i class="fa fa-trash"></i></a>
                        </button>
                      </form>
                    </td>
                    <td>
                      <form action="add_user.html">
                        <button type="button" class="btn btn-success">
                          <a href="{% url 'backend_app:edit_user' pk=key.id %}"><i class="fa fa-pencil-square-o"></i></a>
                        </button>
                      </form>
                    </td>
                  </tr>  
                  {% endfor %} 
                  {% endif %} 
                </table>
                </div>
              </div>
          </div>
        </div>
      </div>

    </div>

{% endblock %}